services:
  redis:
    image: redis:latest
    container_name: simple_redis_container
    ports:
      - "6379:6379"
  app:
    build: ./app
    image: build_app
    container_name: build_app_container
    depends_on:
      - redis
