# Generated by Django 5.2.4 on 2025-08-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnsBoardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('author', models.CharField(max_length=50, verbose_name='投稿者')),
                ('snsimage', models.ImageField(upload_to='', verbose_name='画像')),
                ('notice_level', models.CharField(choices=[('danger', '高'), ('warning', '中'), ('primary', '低'), ('light', '無')], default='light', max_length=50, verbose_name='通知レベル')),
                ('good', models.IntegerField(blank=True, default=1, null=True, verbose_name='いいね数')),
                ('read', models.IntegerField(blank=True, default=1, null=True, verbose_name='既読数')),
                ('read_users', models.TextField(blank=True, default='', null=True, verbose_name='既読ユーザー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
        ),
    ]
