# Generated by Django 5.2.4 on 2025-08-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsboardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsboardmodel',
            name='snsimage',
            field=models.ImageField(upload_to='images/', verbose_name='画像'),
        ),
    ]
