services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ebook_ex
      - MYSQL_USER=development
      - MYSQL_PASSWORD=password
    ports:
      - "4306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
volumes:
  mysql_data:
